<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CMClientCenter.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <LangVersion>preview</LangVersion>
    
    <!-- Verhindert doppelten Program/Main durch WinUI-Codegenerator -->
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <ApplicationIcon>CMClientCenter.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="CMClientCenter.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CMClientCenter.Core\CMClientCenter.Core.csproj" />
    <ProjectReference Include="..\CMClientCenter.PowerShell\CMClientCenter.PowerShell.csproj" />
    <ProjectReference Include="..\CMClientCenter.Shared\CMClientCenter.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250228001" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" PrivateAssets="all" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.*" />
  </ItemGroup>
</Project>
